services:
  redis:
    image: redis:7
    ports:
      - "6380:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis